### ISSUE TITLE
HTTP Error 500.1002 - Internal Server Error

### ISSUE THREAD

**Issue by icyice80** [tjanczuk/iisnode#391]
I am trying to host prerender which is a node.js app inside IIS on my windows server 2008 Enterprise R2. Prerender runs fine via the command line. if I try to host it with IISNode. I keep getting the error below:

Application has thrown an uncaught exception and is terminated:
Error: write ENOTSUP - cannot write to IPC channel.
    at errnoException (child_process.js:1001:11)
    at ChildProcess.target.send (child_process.js:465:16)
    at Worker.send (cluster.js:406:21)
    at sendInternalMessage (cluster.js:399:10)
    at handleResponse (cluster.js:177:5)
    at respond (cluster.js:192:5)
    at Object.messageHandler.queryServer (cluster.js:247:5)
    at handleMessage (cluster.js:197:32)
    at ChildProcess.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)

On the Windows Task Manager, I could see node.exe started then disappeared. 

Any ideas would be greatly appreciated as I am out of clues now. 

Thank you. 

Bing

**Comment by juanfranblanco** [comment]
Same issue on Azure websites, trying to run pencilblue cms

**Comment by tysonnero** [comment]
I'm having the same issue as @icyice80 trying to run prerender with iisnode.

**Comment by rauluranga** [comment]
any news on this issue??

**Comment by rramachand21** [comment]
iisnode does not support cluster which prerender uses internally as @tysonnero  mentioned above. Cluster does not support named pipes on windows which is the main issue here.

**Comment by IronMania** [comment]
add node to the application settings on Azure. this helps at least for the azure problem
![image](https://user-images.githubusercontent.com/724592/33071609-7f581e5e-cebc-11e7-950c-3664032c1dd5.png)

> Same issue on Azure websites, trying to run pencilblue [cms]

**Comment by TomasKatz** [comment]
same issue here any news?

**Comment by allens01** [comment]
I had this same issue. The problem for me was that the account that the application pool was running under did not have write access to the filesystem where the IIS node logs were being written. I changed the identity to the System account and it worked.

**Comment by yarick123** [comment]
I had the same problem. It was caused by not enough rights of the application pool user, when the package "win-ca" was used.

As a temporary solution, instead of using "win-ca" we disabled checking of the local certificates.

**Comment by kierandrewett** [comment]
Hi, how did you do this exactly? @allens01

**Comment by allens01** [comment]
@EnderDev I did that in the Advanced Settings of the application pool, I set the identity to LocalSystem.
![image](https://user-images.githubusercontent.com/2064227/52466472-42e7c200-2b7a-11e9-9da8-ce7cf8952fdc.png)

This is not necessary the best solution as some companies might raise this as a security concern as the app has higher rights than required. Alternatively, if you app pool is running under the context of a service account, you can try giving that account rights to the directory where the IIS node logs are written?
