### ISSUE TITLE
Using cluster in Azure Website

### ISSUE THREAD

**Issue by gsferreira** [tjanczuk/iisnode#419]
Hi!

I confess that I don't know if this is an issue of iisnode and if this is the right place to ask it, but here I go.

I'm trying to use the node.js cluster module as the example [here](https://github.com/tjanczuk/iisnode/blob/57401b0554af3b183be39e3762300b0b3b270d28/test/performance/www/cluster/server.js), but I got the following error when I run it on an Azure Web Site.

```
Thu Feb 19 2015 14:54:56 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: write ENOTSUP - cannot write to IPC channel.
at errnoException (child_process.js:1001:11)
at ChildProcess.target.send (child_process.js:465:16)
at Worker.send (cluster.js:406:21)
at sendInternalMessage (cluster.js:399:10)
at handleResponse (cluster.js:177:5)
at respond (cluster.js:192:5)
at Object.messageHandler.queryServer (cluster.js:247:5)
at handleMessage (cluster.js:197:32)
at ChildProcess.emit (events.js:117:20)
at handleMessage (child_process.js:322:10)
```

What am I doing wrong? Is the cluster supported by iisnode?

**Comment by rramachand21** [comment]
cluster is not supported with iisnode since cluster does not support named pipe server on windows.

**Comment by gsferreira** [comment]
Thanks @rramachand21
