### ISSUE TITLE
Permissions: Can't access a mapped network drive path

### ISSUE THREAD

**Issue by ostelaymetaule** [tjanczuk/iisnode#508]
Hello there!
I have some problems with accessing a path with FS commands if this path refers a network drive. 

Node app and IISNODE runs under a user with permissions granted to the given directory on a network drive like` 'P:/data/something/gateway/temp'`. This user has NO permissions on ancessor directories.
If i run` fs.writeFile('P:/data/something/gateway/temp/test1.txt', 'data!', function(error){});` from a standard node app or from the repl it works like a charm. 
Running it whithin IISNODE hosted app gives 

> Error: ENOENT: no such file or directory

Or in case of multer - 

> RangeError: Maximum call stack size exceeded
>     at String.slice (native)
>     at Object.resolve (path.js:258:27)
>     at Object._makeLong (path.js:666:32)
>     at Object.fs.statSync (fs.js:981:34)
>     at sync (C:\Program Files\iisnode\www\msgattach\node_modules\mkdirp\index.js:90:32)
>     at sync (C:\Program Files\iisnode\www\msgattach\node_modules\mkdirp\index.js:79:24)

which is the same error which pops while trying to access a directory without permissions to the current user.

**Comment by ostelaymetaule** [comment]
Correction:

It was not a problem of IISNODE or permissions. The user which was running iisnode had no P: drive installed.
