### ISSUE TITLE
Even After all permissions given to app pool identity the error is coming 

### ISSUE THREAD

**Issue by homesfy** [tjanczuk/iisnode#521]
Application has thrown an uncaught exception and is terminated:
Error: EPERM: operation not permitted, realpath 'D:\Inetpub\vhosts\homesfy.in\staging.homesfy.in\express\server.js'
    at Error (native)
    at Object.realpathSync (fs.js:1574:18)
    at Function.Module._findPath (module.js:167:25)
    at Function.Module._resolveFilename (module.js:438:25)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\iisnode\interceptor.js:210:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by homesfy** [comment]
please help me out with this issue

**Comment by devotis** [comment]
What user is your application pool running on? What are the permissions you gave to the folder that the websites uses. Double check that the website is actually using that application pool.

If you fixed this issue in the meantime please close this issue. And please share anything you learned concerning this issue if you like.
