### ISSUE TITLE
IISNode and python-shell

### ISSUE THREAD

**Issue by NamTThai** [tjanczuk/iisnode#550]
I use `python-shell` module to run some python scripts in my `iisnode` application. It works fine in `nodejs`, but produces the following error in `iisnode`:

```
executable: "C:\Program Files\Anaconda2\python.exe"
exitCode: 3221225794
options: null
script: "python\gaussian-blur.py"

console.log(err.stack);
Error: process exited with code 3221225794
    at terminateIfNeeded (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:100:23)
    at ChildProcess.<anonymous> (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:88:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

and 

```
{ [Error: Unable to register TclNotifier window class



This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

]
  executable: 'C:\\Program Files\\Anaconda2\\python.exe',
  options: null,
  script: 'python\\gaussian-blur.py',
  args: [ '2' ],
  exitCode: 3 }
Error: Unable to register TclNotifier window class


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.


    at PythonShell.parseError (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:190:17)
    at terminateIfNeeded (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:98:28)
    at Socket.<anonymous> (C:\Program Files\iisnode\cio-monitor\node_modules\python-shell\index.js:78:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

The python script is just a simple print statement

Do you guys have any idea?

**Comment by NamTThai** [comment]
@extrabacon/python-shell/issues/69

**Comment by NamTThai** [comment]
extrabacon/python-shell/issues/#69

**Comment by NamTThai** [comment]
extrabacon/python-shell#69
