### ISSUE TITLE
iisnode encountered an error when processing the request.

### ISSUE THREAD

**Issue by electron36** [tjanczuk/iisnode#554]
iisnode encountered an error when processing the request.

```
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error

```
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

Application has thrown an uncaught exception and is terminated:
C:\Program Files\iisnode\www\FoodTruck-API\src\index.js:1
```
(function (exports, require, module, __filename, __dirname) { import http from 'http';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\iisnode\interceptor.js:210:1)
    at Module._compile (module.js:570:32)
```

**Comment by spongessuck** [comment]
The module just runs Node. Whether or not es2015 is supported depends on Node itself.
