### ISSUE TITLE
Internal Server Error 1002

### ISSUE THREAD

**Issue by e06widu** [tjanczuk/iisnode#564]
I hosted my node app on iis server but it gives me following error. I have given full access to both IIS_IUSRS and IUSR.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

```
Application has thrown an uncaught exception and is terminated:
Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (C:\DP\DPWebUI\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\DP\DPWebUI\server.js:39:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

My server.js is as follows

```
'use strict';

// Module dependencies.
var express = require('express'),
    path = require('path'),
    fs = require('fs'),
    cors = require('cors'),
    methodOverride = require('method-override'),
    morgan = require('morgan'),
    bodyParser = require('body-parser');

var app = module.exports = exports.app = express();

app.locals.siteName = "IOS IBE";
app.use(cors());
//cors and preflight filtering
app.all('*', function (req, res, next) {
//preflight needs to return exact request-header
    res.set('Access-Control-Allow-Headers',
        req.headers['access-control-request-headers']);
    if ('OPTIONS' == req.method)
        return res.send(204);
    next();
});
app.use(express.static(__dirname + '/public'));

app.get('/*', function (req, res) {
    res.sendFile(__dirname + '/public/index.html');
});

app.use(methodOverride());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));

// Start server
var port = 80;
app.listen(port);
```

**Comment by nearwood** [comment]
We have just recently received the same 500/1002 error on multiple machines running iisnode. Code commits don't seem related. Might be Windows or IIS updates. We are unable to see logs all of the sudden as well though, so the underlying issue may or may not be the same.

**Comment by e06widu** [comment]
Since IIS controls the base address for all HTTP listeners, a node.js application must use the listen address provided by the iisnode module through the process.env.PORT environment variable rather than specify its own.
So I get the port using  process.env.PORT and it solve my problem.

**Comment by phobos04** [comment]
@e06widu, please where did you specify the port using `process.env.PORT` to solve the problem?
Thank you

**Comment by pbaio** [comment]
@phobos04 

You you want to do something like this

```javascript
const express = require('express')
const server = express()

const port = process.env.PORT || 1337

// Middleware and Routes go here

server.listen(port, () => {
  console.log(`Listening on ${port}`)
})
```
