### ISSUE TITLE
logging-errors Unexpected token >

### ISSUE THREAD

**Issue by szentesmarci** [tjanczuk/iisnode#625]
On azure app service from one point
my application stopped logging anything.
In the diagnostic dump I found a file which says:
Fri Mar 02 2018 03:38:51 GMT+0100 (W. Europe Standard Time): Disabling Azure Drive logging after 43200000ms since it was enabled
Fri Mar 02 2018 16:57:20 GMT+0100 (W. Europe Standard Time): Application has thrown an uncaught exception and is terminated:
SyntaxError: Unexpected token >
    at Module._compile (module.js:434:25)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\Program Files (x86)\iisnode\interceptor.js:459:1)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
Fri Mar 02 2018 23:27:45 GMT+0100 (W. Europe Standard Time): Disabling Azure Drive logging after 43200000ms since it was enabled
Wed Mar 07 2018 21:26:26 GMT+0100 (W. Europe Standard Time): Disabling Azure Drive logging after 43200000ms since it was enabled
Wed Mar 14 2018 02:22:27 GMT+0100 (W. Europe Standard Time): Disabling Azure Drive logging after 43200000ms since it was enabled

And I did not change the web.config whatsoever

**Comment by jordan-mcrae** [comment]
We were able to solve this issue by explicitly defining the path to our node.exe file in our web.config.

For example...

```
<iisnode 
nodeProcessCommandLine="C:\path\to\nvm\v10.15.0\node.exe" />
```

**Comment by siddthesciencekid** [comment]
@jordan-mcrae 

I'm running into the same problem even though I'm also explicitly defining the path, would you mind posting your web.config file or a redacted version so I can see if there are any differences?

**Comment by infiniteloopltd** [comment]
I had the same issue.

I had installed an x86 version of Node on a 64 bit server. So, I installed the 64 bit version of Node, then ran an iisreset. 

No config changes needed.
