### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by CrispyBacon1999** [tjanczuk/iisnode#688]
I'm deploying a NextJS app to an Azure App Service, but after it deploys successfully, I get the following error message.
```
Tue Aug 17 2021 20:30:04 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
SyntaxError: Unexpected token {
    at Module._compile (module.js:434:25)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\Program Files\iisnode\interceptor.js:459:1)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)

```

It shows up every time the page loads, and the page instantly just gives a 500 errror. Any ideas on what could be going wrong?

```
WEBSITE_NODE_DEFAULT_VALUE=14-lts
```

**Comment by websolut** [comment]
Node version you have in the app settings is not available in Azure.

**Comment by ToNGocDuy** [comment]
you should install all nodejs, iisnode,  and iis server same 64bit or 84-bit

**Comment by lextm** [comment]
The current version of iisnode does not support ES6 Modules syntax, so such issues cannot easily fix. You should switch to an alternative. Read Azure/iisnode#146 to learn more.
